model:
  task: matching
  pretrain_type: mmae
  kwargs: configs/croco_small_model_args.yaml
  pretrained_ckpt: exp/mmae-habitat_sim-CroCo_small-curope/checkpoint-49.pth

inference:
  reciprocity: true
  suppress_1st_token: false
  attn_layers_adopted: null
  temperature: 0.02